<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/>
    </parent>

    <groupId>br.com.fiap</groupId>
    <artifactId>tech-challenge-fase3</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Tech Challenge Fase 3</name>
    <description>Sistema hospitalar de agendamento, historico e notificacoes</description>

    <modules>
        <module>agendamento-service</module>
        <module>historico-service</module>
        <module>notificacao-service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jjwt.version>0.12.6</jjwt.version>
        <graphql-extended-scalars.version>22.0</graphql-extended-scalars.version>
    </properties>

</project>
